name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on:
      - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install npm dependencies
        run: npm i
      - name: build and push dist folder
        run: |
          npm run build || echo -n
          git config --global user.name "Github Actions"
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github ${GITHUB_REF} --ff-only || echo -n
          git commit -am "Update dist/ (`npm run build`)" && git push github HEAD:${GITHUB_REF} || echo -n
