name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on:
      - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install npm dependencies
        run: npm i
      - name: lint and push automatic fixes
        run: sh .github/workflows/lint.sh
